config/routes.rb
Jewellover::Application.routes.draw do

  get "lists_controller/index"

  resources :wallets
  resources :authentications

  devise_for :retailer, :controllers => {:registrations => "retailer/registrations"}, :skip => [:sessions, :password] do
    get "retailer/signup" => "retailer/registrations#new"
  end

  match '/auth/:provider/callback', :to => 'authentications#create'
  match '/auth/failure', :to => 'authentications#failure'

  match "/notify_url" => "paypal_adaptive_payment_callbacks#notify", :as => :paypal_notify
  resources :paypal_adaptive_payment_callbacks

  resources :bids
  resource :user_preferences
  resources :stores do
    resources :products, :only => [:index, :show]
  end

  resource :contact do
    post :store
  end

  match "/" => "products#homepage"
  match "/products" => "products#index"
  match "/categories" => "products#categories"
  match "/upcoming" => "products#upcoming"
  match "/recent" => "products#latest"

  match "/testimonials" => "posts#testimonials"
  match "/whats_new" => "posts#whats_new"

  match "/my_dashboard" => "dashboard#index", :as => :my_dashboard
  match "/my_orders" => "orders#index", :as => :my_orders
  match "/my_offers" => "bids#index", :as => :my_offers
  match "/my_watchlist" => "watchlists#index", :as => :my_watchlist
  match "/my_account" => "users#edit", :as => :my_account
  match "/my_wallet" => "wallets#show", :as => :my_wallet

  match "/server_time" => "spree/base#server_time"
  match "/site_product_info" => "spree/base#site_product_info"
  match "/products/view_style" => "products#view_style"

  match "/v2" => "products#homepage"

  match '/users/add_product_to_watchlist' => 'users#add_product_to_watchlist', :via => :post
  match '/users/remove_product_from_watchlist' => 'users#remove_product_from_watchlist', :via => :post

  match '/t/*id' => 'taxons#show', :as => :nested_taxons

  namespace :api do

    match "/taxonomies" => "products#taxonomies"

    resources :retailers, :only => [:show, :index] do
      resources :products, :only => [:show, :index, :create, :update] do
        match "/images/:image_id" => "products#delete_image", :via => :delete
      end
    end
    resources :products, :only => [:index, :show]

  end

  namespace :admin do

    resources :lists do
      member do
        match "upload_csv" => "lists#upload_csv"
        get :download_csv
      end

      resources :list_recipients, :except => [:edit, :update, :show], :as => :contacts
    end
    resources :coupons
    resources :posts
    resources :users do
      post :toggle_ban, :on => :member
    end
    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        get :leveredge_total
      end
    end
    resources :stores do
      member do
        post :toggle_website
        post :toggle_facebook
      end
    end
    resources :products do
      member do
        post :product_campaign
        post :toggle_relist
        get :reset
      end
    end

  end

  namespace :retailer do

    match "/" => 'products#index'
    match "/support" => 'static#support', :as => :support

    resource :retailer_detail
    resource :settings

    resources :stores
    resources :zones
    resources :users
    resources :countries do
      resources :states
    end
    resources :states
    resources :promotions
    resources :tax_categories
    resources :configurations
    resources :products do
      member do
        get :clone
        get :finish
        get :start
        post :archive
        post :toggle_relist
        post :refund
      end
      resources :product_properties
      resources :images
      resources :variants
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
          get :finish
        end
        collection do
          post :available
          get :selected
        end
      end
    end
    resources :option_types
    resources :properties do
      collection do
        get :filtered
      end
    end
    resources :prototypes do
      member do
        get :select
      end
      collection do
        get :available
      end
    end
    resource :inventory_settings
    resources :google_analytics
    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
        get :user
      end
      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end
    resource :general_settings
    resources :taxonomies do
      member do
        get :get_children
      end
      resources :taxons
    end
    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end
    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource :tax_settings
    resources :calculators
    resources :product_groups do
      resources :product_scopes
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < Spree::BaseController

  before_filter :authenticate_user!
  before_filter :check_for_orders, :only => :populate

  helper :products

  def index
    @orders = Order.select { |o| o.user_id == current_user.id }
  end

  def show
    @order = Order.find_by_number(params[:id])
    @product = @order.product
    @store = @product.store
  end

  def update

    @order = current_order

    if @order.update_attributes(params[:order])
      @order.line_items = @order.line_items.select { |li| li.quantity > 0 }
      redirect_to cart_path
    else
      render :edit
    end

  end

  def edit
    @order = current_order
  end

  # Adds a new item to the order (creating a new order if none already exists)
  #
  # Parameters can be passed using the following possible parameter configurations:
  #
  # * Single variant/quantity pairing
  # +:variants => {variant_id => quantity}+
  #
  # * Multiple products at once
  # +:products => {product_id => variant_id, product_id => variant_id}, :quantity => quantity +
  # +:products => {product_id => variant_id, product_id => variant_id}}, :quantity => {variant_id => quantity, variant_id => quantity}+
  def populate

    session[:order_id] = nil
    @current_order = nil

    @order = current_order(true)


    params[:variants].each do |variant_id, quantity|

      quantity = 1
      @order.add_variant(Variant.find(variant_id), quantity) if quantity > 0

    end if params[:variants]


    #update product state to cart
    @order.product.cart

    # we want to delete the Kill_product Delayed::Job because it has just been SOLD!... well 'carted' anyway
    # If they push buy now in the final seconds this could still run the Job(IE Relist or expire) if it doesnt get called fast enough..
    # Really in theory theres no way to control the JOb if its set to run within the time it takes to
    # reach this point. All will come down to speed of the connection/site...
    @order.product.delete_kill_job

    #set owner details for order
    @order.update_attributes(:retailer_id => @order.product.retailer_id)


    redirect_to cart_path

  end

  def empty
    if @order = current_order
      #clear session order id because each order will be New when buy now selected.
      #NOTE nil is true and false is false in current_order module
      session[:order_id] = nil
      @order.line_items.destroy_all
      @order.product.cart unless @order.product.sold
      @order.delete
    end
    redirect_to cart_path
  end

  def check_for_orders

    existing_orders = Order.joins(:line_items).where("line_items.variant_id = ?", params[:variants].first[0])

    unless existing_orders.empty? ||
        %w(canceled refunded).include?(existing_orders.last.state)
      redirect_to session[:user_return_to], :alert => "This product has been sold!"
    end

  end


  def accurate_title
    I18n.t(:shopping_cart)
  end

end

app/controllers/retailer/orders_controller.rb
class Retailer::OrdersController < Retailer::BaseController
  require 'spree/gateway_error'
  resource_controller
  before_filter :initialize_txn_partials
  before_filter :initialize_order_events
  before_filter :load_object, :only => [:fire, :resend, :history, :user]
  before_filter :ensure_line_items, :only => [:update]

  update do
    flash nil
    wants.html do
      if !@order.line_items.empty?
        unless @order.complete?

          if params[:order].key?(:email)
            @order.shipping_method = @order.available_shipping_methods(:front_end).first
            @order.create_shipment!
            redirect_to edit_retailer_order_shipment_path(@order, @order.shipment)
          else
            redirect_to user_retailer_order_path(@order)
          end

        else
          redirect_to retailer_order_path(@order)
        end
      else
        render :action => :new
      end
    end
  end

  index.before do

    @orders = @search.where(:retailer_id => current_user.id)

    @orders = @orders.paginate(:page => params[:page])

  end

  show do
    @product = Product.first
  end



  def new
    @order = @object = Order.create
  end

  def fire
    # TODO - possible security check here but right now any admin can before any transition (and the state machine
    # itself will make sure transitions are not applied in the wrong state)
    event = params[:e]
    if @order.send("#{event}")
      flash.notice = t('order_updated')
    else
      flash[:error] = t('cannot_perform_operation')
    end
  rescue Spree::GatewayError => ge
    flash[:error] = "#{ge.message}"
  ensure
    redirect_to :back
  end

  def resend
    OrderMailer.confirm_email(@order, true).deliver
    flash.notice = t('order_email_resent')
    redirect_to :back
  end

  def user
    @order.build_bill_address(:country_id => Spree::Config[:default_country_id]) if @order.bill_address.nil?
    @order.build_ship_address(:country_id => Spree::Config[:default_country_id]) if @order.ship_address.nil?
  end

  private

  def object
    @object ||= Order.find_by_number(params[:id], :include => :adjustments) if params[:id]
    return @object || current_order
  end

  def collection
    params[:search] ||= {}
    @show_only_completed = params[:search][:completed_at_is_not_null].present?
    params[:search][:meta_sort] ||= @show_only_completed ? 'completed_at.desc' : 'created_at.desc'


    if !params[:search][:created_at_greater_than].blank?
      params[:search][:created_at_greater_than] = Time.zone.parse(params[:search][:created_at_greater_than]).beginning_of_day rescue ""
    end

    if !params[:search][:created_at_less_than].blank?
      params[:search][:created_at_less_than] = Time.zone.parse(params[:search][:created_at_less_than]).end_of_day #rescue ""
    end

    if @show_only_completed
      params[:search][:completed_at_greater_than] = params[:search].delete(:created_at_greater_than)
      params[:search][:completed_at_less_than] = params[:search].delete(:created_at_less_than)
    end

    @search = Order.metasearch(params[:search])


    @collection = Order.metasearch(params[:search]).paginate(
                                   :include  => [:user, :shipments, :payments],
                                   :per_page => Spree::Config[:orders_per_page],
                                   :page     => params[:page])
  end

  # Allows extensions to add new forms of payment to provide their own display of transactions
  def initialize_txn_partials
    @txn_partials = []
  end

  # Used for extensions which need to provide their own custom event links on the order details view.
  def initialize_order_events
    @order_events = %w{cancel resume}
  end

  def ensure_line_items
    load_object
    if @order.line_items.empty?
      @order.errors.add(:line_items, t('errors.messages.blank'))
      render :edit
    end
  end

end

app/helpers/orders_helper.rb
module OrdersHelper


  # NOT IN USE
  def state_explination(state)
    msg = nil
    case state
      when "complete"
        msg = "Complete orders are orders that you have successfully paid for.
              Once complete all you have to do is wait for the product to arrive."
      when "cart"
        msg = "These orders you have yet to pay for, view each order below and complete the purchase."
      when "delivery"
        msg = "We are still waiting for you to set the delivery method and complete the purchase of these products."
      when "payment"
        msg = "."
    end

    return msg
  end

  def checkout_button(order)

    if order.state == "cart"
      link = link_to "Checkout NOW!", checkout_path(:order_id => order.number), :class => "button primary checkout"
    else
      link = link_to "Checkout NOW!", edit_order_checkout_path(order, :order_id => order.number), :class => "button primary checkout"
    end

    return link
  end

end

app/views/admin/orders/_add_product.html.erb
<div id="add-line-item">
  <fieldset>
    <legend><%= t('add_product') %></legend>
    <div style="float:left;width:65%;margin-right:5%;">
      <%= label_tag :add_product_name, t("name_or_sku") %>
      <%= text_field_tag :add_product_name, nil, :class => 'fullwidth title'  %>
      <%= hidden_field_tag :add_variant_id %>
    </div>
    <div style="float:left;width:10%;margin-right:5%;">
      <%= label_tag :add_quantity, t("qty") %>
      <%= text_field_tag :add_quantity,  1 , :class => 'fullwidth title'  %>
    </div>
    <div style="float: left; width: 15%; padding-top: 17px;">
      <%= link_to text_for_button_link(t("add"), :icon => 'add'),
            retailer_order_line_items_url(@order),
            {:id => 'add_line_item_to_order', :class => 'button', 'data-update' => 'order-form-wrapper'} %>
    </div>

  </fieldset>
</div>

app/views/admin/orders/_form.html.erb
<%= render 'shared/error_messages', :target => @order %>
<% if @line_item.try(:errors).present? %>
  <%= render 'shared/error_messages', :target => @line_item %>
<% end %>

<%= form_for(@order, :url => retailer_order_url(@order), :html => { :method => :put}) do |f| %>
  <%= f.hidden_field :number %>
  <table class="index">
    <tbody id='line-items'>
      <tr>
        <%= hook :admin_order_form_line_items_headers do %>
          <th><%= t('item_description') %></th>
          <th class="price"><%= t('price') %></th>
          <th class="qty"><%= t('qty') %></th>
          <th class="total"><span><%= t('total') %></span></th>
        <% end %>
        <th class="orders-actions"><%= hook :admin_order_form_line_items_header_actions %></th>
      </tr>
      <%= f.fields_for :line_items do |li_form| %>
        <%= render :partial => "retailer/orders/line_item", :locals => { :f => li_form } %>
      <% end %>
    </tbody>
    <%= hook :admin_order_form_subtotal do %>
      <tbody id='subtotal'>
        <tr id="subtotal-row">
          <td colspan="3"><b><%= t('subtotal') %>:</b></td>
          <td class="total"><span><%= number_to_currency @order.item_total %></span></td>
          <td></td>
        </tr>
      </tbody>
    <% end %>
    <%= hook :admin_order_form_adjustments do %>
      <tbody id="order-charges">
        <% @order.adjustments.each do |adjustment| %>
          <tr>
            <td colspan="3"><strong><%= adjustment.label %></strong></td>
            <td class="total"><span><%= number_to_currency adjustment.amount %></span></td>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
    <%= hook :admin_order_form_total do %>
      <tbody id='order-total'>
        <tr>
          <td colspan="3"><b><%= t('order_total') %>:</b></td>
          <td class="total"><span id="order_total"><%= number_to_currency @order.total %></span></td>
          <td></td>
        </tr>
      </tbody>
    <% end %>
  </table>

  <% hook :admin_order_form_buttons do %>
    <p class="form-buttons">
      <%= button @order.complete? ? t('update') : t('continue') %>
      <%= t("or") %> <%= link_to t("actions.cancel"), retailer_orders_url %>
    </p>
  <% end %>

<% end %>

<script type="text/javascript">
  <%= render 'admin/shared/update_order_state.js' %>
</script>

<%= javascript_include_tag 'admin/orders/edit_form.js' %>

app/views/admin/orders/_line_item.html.erb
<tr id="<%= dom_id(f.object) %>">
  <%- locals = {:f => f} %>
  <%= hook :admin_order_form_line_item_row, locals do %>
    <td width="300"><%=f.object.variant.product.name%> <%= "(" + variant_options(f.object.variant) + ")" unless f.object.variant.option_values.empty? %></td>
    <td valign="top" class="price"><%= number_to_currency f.object.price %></td>
    <td valign="top" class="qty"><%=f.text_field :quantity, :style => "width:30px;", :class => "qty", :disabled => true %></td>
    <td valign="top" class="total"><%= number_to_currency (f.object.price * f.object.quantity)%></td>
  <% end %>
  <td>
    <%= hook :admin_order_form_line_item_actions, locals do %>
      <%# link_to_delete f.object, {:url => retailer_order_line_item_url(@order.number, f.object),
                                    :dataType => "html" ,
                                    :success => "function(r){ jQuery('#order-form-wrapper').html(r);}"} %>
    <% end %>
  </td>
</tr>

app/views/admin/orders/_user_form.html.erb
<h3><%= t("customer_details") %></h3>
<table class="index">
  <thead>
    <th colspan="8"><%= t('account') %></th>
  </thead>
  <tbody>
    <tr>
      <td class="lbl-col"><%= f.label :email, t(:email)+':' %></td>
      <td class="val-col" colspan="3"><%= f.text_field :email, :class => "fullwidth" %></td>
      <td class="lbl-col"></td>
      <td class="val-col" colspan="3">
        <% if @order.completed? %>
          <%= @order.user.nil? ? "Yes" : "No" %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<h3><%= Address.model_name.human(:count => 2) %></h3>
<%= f.fields_for :bill_address do |ba_form|  %>
  <%= render :partial => "retailer/shared/address_form", :locals => {:f => ba_form, :name => t('billing_address'), :use_billing => false} %>
<% end %>

<%= f.fields_for :ship_address do |sa_form|  %>
  <%= render :partial => "retailer/shared/address_form", :locals => {:f => sa_form, :name => t('shipping_address'), :use_billing => true} %>
<% end %>

<p class="form-buttons">
  <%= button @order.cart? ? t('continue') : t('update') %>
</p>

app/views/admin/orders/edit.html.erb
<%= csrf_meta_tag %>
<div class='order-links'>
  <%= hook :admin_order_edit_buttons do %>
    <div class='toolbar'>
      <%# event_links %>
    </div>
    <div class='toolbar'>
      <%# button_link_to(t("resend"), resend_retailer_order_url(@order), :method => :post, :icon => 'send-email') if @order.user %>
    </div>
  <% end %>
</div>

<%= render :partial => 'retailer/shared/order_tabs', :locals => {:current => "Order Details"} %>

<%# render :partial => "add_product" %>

<%= hook :admin_order_edit_header do %>
  <%= render "shared/error_messages", :target => @order %>
<% end %>

<%= hook :admin_order_edit_form do %>
  <div id="order-form-wrapper">
    <%= render :partial => 'form', :locals => {:order => @order} %>
  </div>
<% end %>

<% content_for :head do %>
  <%= javascript_tag "var expand_variants = true;" %>
  <%= javascript_include_tag 'admin/orders/edit.js' %>
  <%= stylesheet_link_tag 'admin/edit_orders.css' %>
<% end %>

app/views/admin/orders/history.html.erb
<%= render :partial => 'retailer/shared/order_tabs', :locals => {:current => "History"} %>

<h2><%= t("history")%></h2>

<table class="index">
  <tr>
    <th><%= t("event") %></th>
    <th><%= t("user") %></th>
    <th><%= "#{t('spree.date')}/#{t('spree.time')}" %></th>
  </tr>
  <% @order.state_events.sort.each do |event| %>
    <tr>
      <td><%=t("#{event.name}") %></td>
      <td><%=event.user.email if event.user %></td>
      <td><%=event.created_at.to_s(:date_time24) %></td>
    </tr>
  <% end %>
  <% if @order.state_events.empty? %>
    <tr>
      <td colspan="3"><%= t("none_available") %></td>
    </tr>
  <% end %>
</table>

<%= button_link_to 'Back', retailer_orders_url %>

app/views/admin/orders/index.html.erb
<!--<div class='toolbar order-links'>-->
<!--<%# button_link_to t("new_order"), new_retailer_order_url, :icon => 'add', :id => 'admin_new_order' %>-->
<!--</div>-->

<%= render :partial => 'retailer/shared/order_sub_menu' %>
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= link_to_with_icon "printer", "Print Page", "javascript:window.print()" %>
    </li>
  </ul>
</div>






<h1><%= t("listing_orders") %></h1>


<table class="index" id='listing_orders'>
  <thead>
  <tr>
    <%= hook :admin_orders_index_headers do %>
        <% if @show_only_completed %>
            <th><%= sort_link @search, :completed_at, t("activerecord.attributes.order.completed_at") %></th>
        <% else %>
            <th><%= sort_link @search, :created_at, t("order_date") %></th>
        <% end %>
        <th><%= sort_link @search, :number, t("order_number") %></th>
        <th>Stock Code</th>
        <th>Product Name <%# sort_link @search,  %></th>
        <th><%= sort_link @search, :state, "Order Status" %></th>
        <th><%= sort_link @search, :payment_state, t("payment_state") %></th>
        <th><%= sort_link @search, :shipment_state, t("shipment_state") %></th>
        <th><%= sort_link @search, :email, t("customer") %></th>
        <th>Full Name</th>
        <th><%= sort_link @search, :total, "Sold For" %></th>
    <% end %>

  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <%- locals = {:order => order} %>
        <%= hook :admin_orders_index_rows, locals do %>
            <td><%= (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
            <td><%= order.number %></td>
            <td><%= order.products.first.try(:sku) %></td>
            <td><%= order.products.first.try(:name) %></td>
            <td><%= t("order_state.#{order.state.downcase}") %></td>
            <td><%= order.payment_state if order.payment_state %></td>
            <td><%= order.shipment_state %><%# link_to t("shipment_states.#{order.shipment_state}"), retailer_order_shipments_path(order) if order.shipment_state %></td>
            <td><%= order.email %></td>
            <td><%= link_to "#{order.bill_address.try(:firstname)} #{order.bill_address.try(:lastname)}", user_admin_order_url(order) %></td>
            <td><%= number_to_currency order.total %></td>
        <% end %>

      </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate(@orders, :previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;") %>

<% content_for :sidebar do %>
    <div class="box">
      <h3>Search / Reports Filter</h3>
      <%= form_for [:admin, @search] do |f| %>
          <%- locals = {:f => f} %>
          <%= hook :admin_orders_index_search, locals do %>
              <label><%= t("date_range") %></label><br/>

              <div class="yui-g date-range-filter">
                <div class="yui-u sub-field first">
                  <%= f.spree_date_picker :created_at_greater_than %>
                  <br/>
                  <label class="sub"><%= t("start") %></label>
                </div>
                <div class="yui-u sub-field">
                  <%= f.spree_date_picker :created_at_less_than %>
                  <br/>
                  <label><%= t("stop") %> </label>

                </div>

              </div>

              <p><label><%= t("status") %></label><br/>
                <%= f.select :state_equals, Order.state_machines[:state].states.collect { |s| [t("order_state.#{s.name}"), s.value] }, {:include_blank => true} %>
              </p>

              <p><label><%= t 'order_number' %></label><br/>
                <%= f.text_field :number_like, :size=>25 %></p>

              <p>
                <label><%= t 'email' %></label><br/>
                <%= f.text_field :email_like, :size=>25 %>
              </p>

              <p>
                <label><%= t 'first_name_begins_with' %></label><br/>
                <%= f.text_field :bill_address_firstname_starts_with, :size=>25 %>
              </p>

              <p>
                <label><%= t 'last_name_begins_with' %></label><br/>
                <%= f.text_field :bill_address_lastname_starts_with, :size=>25 %>
              </p>

              <p>
                <%= f.check_box :completed_at_is_not_null, {:checked => @show_only_completed}, "1", "" %>
                <label>
                  <%= t("show_only_complete_orders") %>
                </label>
              </p>
          <% end %>
          <%= hook :admin_orders_index_search_buttons, locals do %>
              <div class="form-buttons"><%= f.submit "Search", :class => "button search" %></div>
          <% end %>
      <% end %>
    </div>
<% end %>

app/views/admin/orders/new.html.erb
<%= render :partial => 'admin/shared/order_tabs', :locals => {:current => "Order Details"} %>
<%= csrf_meta_tag %>

<%= hook :admin_order_new_header do %>
  <h2><%= t("new_order")%></h2>
  <%= render 'shared/error_messages', :target => @order %>
<% end %>

<%= render :partial => "add_product" %>

<%= hook :admin_order_new_form do %>
  <div id="order-form-wrapper">
    <%= render :partial => "form" %>
  </div>
<% end %>

<% content_for :head do %>
  <%= javascript_tag "var expand_variants = true;" %>
  <%= javascript_include_tag 'admin/orders/edit.js' %>
<% end %>

app/views/admin/orders/show.html.erb
<div class='toolbar order-links'>
  <%= hook :admin_order_show_buttons do %>
    <%= button_link_to t("cancel"), fire_retailer_order_url(@order.number, {:e => "cancel"}), :icon => 'delete', :confirm => 'are you sure?' if @order.can_cancel? %>
    <%= button_link_to t("edit"), edit_retailer_order_url(@order.number), :icon => 'edit' %>
  <% end %>
</div>

<%= render :partial => 'retailer/shared/order_tabs', :locals => {:current => "Order Details"} %>

<%= hook :admin_order_show_addresses do %>
  <% if @order.bill_address %>
    <div class='adr'>
      <h4><%= t("bill_address") %></h4>
      <%= render :partial => 'retailer/shared/address', :locals => {:address => @order.bill_address} %>
    </div>
  <% end %>
  <% if @order.ship_address %>
    <div class='adr'>
      <h4><%= t("ship_address") %></h4>
      <%= render :partial => 'retailer/shared/address', :locals => {:address => @order.ship_address} %>
    </div>
    <% end %>
  <hr />
<% end %>

<%= hook :admin_order_show_details do %>
  <%= render :partial => 'retailer/shared/order_details', :locals => {:order => @order} %>
<% end %>

app/views/admin/orders/user.html.erb
<%= render :partial => 'retailer/shared/order_tabs', :locals => {:current => "Customer Details"} %>
<%= csrf_meta_tag %>



<%= render "shared/error_messages", :target => @order %>

<%= form_for(@order, :url => retailer_order_url(@order), :html => { :method => :put}) do |f| %>
  <%= f.hidden_field :number %>
  <%= render :partial => "user_form", :locals => {:f => f} %>
<% end %>

<% content_for :head do %>
  <%= javascript_include_tag 'admin/checkouts/edit.js' %>
<% end %>