config/routes.rb
Jewellover::Application.routes.draw do

  get "lists_controller/index"

  resources :wallets
  resources :authentications

  devise_for :retailer, :controllers => {:registrations => "retailer/registrations"}, :skip => [:sessions, :password] do
    get "retailer/signup" => "retailer/registrations#new"
  end

  match '/auth/:provider/callback', :to => 'authentications#create'
  match '/auth/failure', :to => 'authentications#failure'

  match "/notify_url" => "paypal_adaptive_payment_callbacks#notify", :as => :paypal_notify
  resources :paypal_adaptive_payment_callbacks

  resources :bids
  resource :user_preferences
  resources :stores do
    resources :products, :only => [:index, :show]
  end

  resource :contact do
    post :store
  end

  match "/" => "products#homepage"
  match "/products" => "products#index"
  match "/categories" => "products#categories"
  match "/upcoming" => "products#upcoming"
  match "/recent" => "products#latest"

  match "/testimonials" => "posts#testimonials"
  match "/whats_new" => "posts#whats_new"

  match "/my_dashboard" => "dashboard#index", :as => :my_dashboard
  match "/my_orders" => "orders#index", :as => :my_orders
  match "/my_offers" => "bids#index", :as => :my_offers
  match "/my_watchlist" => "watchlists#index", :as => :my_watchlist
  match "/my_account" => "users#edit", :as => :my_account
  match "/my_wallet" => "wallets#show", :as => :my_wallet

  match "/server_time" => "spree/base#server_time"
  match "/site_product_info" => "spree/base#site_product_info"
  match "/products/view_style" => "products#view_style"

  match "/v2" => "products#homepage"

  match '/users/add_product_to_watchlist' => 'users#add_product_to_watchlist', :via => :post
  match '/users/remove_product_from_watchlist' => 'users#remove_product_from_watchlist', :via => :post

  match '/t/*id' => 'taxons#show', :as => :nested_taxons

  namespace :api do

    match "/taxonomies" => "products#taxonomies"

    resources :retailers, :only => [:show, :index] do
      resources :products, :only => [:show, :index, :create, :update] do
        match "/images/:image_id" => "products#delete_image", :via => :delete
      end
    end
    resources :products, :only => [:index, :show]

  end

  namespace :admin do

    resources :lists do
      member do
        match "upload_csv" => "lists#upload_csv"
        get :download_csv
      end

      resources :list_recipients, :except => [:edit, :update, :show], :as => :contacts
    end
    resources :coupons
    resources :posts
    resources :users do
      post :toggle_ban, :on => :member
    end
    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        get :leveredge_total
      end
    end
    resources :stores do
      member do
        post :toggle_website
        post :toggle_facebook
      end
    end
    resources :products do
      member do
        post :product_campaign
        post :toggle_relist
        get :reset
      end
    end

  end

  namespace :retailer do

    match "/" => 'products#index'
    match "/support" => 'static#support', :as => :support

    resource :retailer_detail
    resource :settings

    resources :stores
    resources :zones
    resources :users
    resources :countries do
      resources :states
    end
    resources :states
    resources :promotions
    resources :tax_categories
    resources :configurations
    resources :products do
      member do
        get :clone
        get :finish
        get :start
        post :archive
        post :toggle_relist
        post :refund
      end
      resources :product_properties
      resources :images
      resources :variants
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
          get :finish
        end
        collection do
          post :available
          get :selected
        end
      end
    end
    resources :option_types
    resources :properties do
      collection do
        get :filtered
      end
    end
    resources :prototypes do
      member do
        get :select
      end
      collection do
        get :available
      end
    end
    resource :inventory_settings
    resources :google_analytics
    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
        get :user
      end
      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end
    resource :general_settings
    resources :taxonomies do
      member do
        get :get_children
      end
      resources :taxons
    end
    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end
    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource :tax_settings
    resources :calculators
    resources :product_groups do
      resources :product_scopes
    end
  end

end

app/controllers/api/retailers_controller.rb
class Api::RetailersController < Api::BaseController

  def index
    if params[:search]
      @retailers = Retailer.where("authentication_token = ?", params[:search])
    else
      @retailers = Retailer.all
    end
    respond_with @retailers
  end

  def show
    @retailer = Retailer.find(params[:id])
    respond_with @retailer
  end

end

app/controllers/retailer/adjustments_controller.rb
class Retailer::AdjustmentsController < Retailer::BaseController
  resource_controller
  belongs_to :order

  update.wants.html { redirect_to collection_url }
  create.wants.html { redirect_to collection_url }
  destroy.success.wants.js { @order.reload && render_js_for_destroy }

end

app/controllers/retailer/base_controller.rb
class Retailer::BaseController < Spree::BaseController
  ssl_required

  before_filter :authenticate_user!
  before_filter :load_retailer


  authorize_resource

  helper :search
  helper 'retailer/navigation'
  layout 'retailer'


  def retailer_products_page
    if session[:back_to_page].present?
      retailer_products_path(:page => session[:back_to_page])
    else
      retailer_products_path
    end
  end

  protected


  def render_js_for_destroy
    render :partial => "/retailer/shared/destroy"
    flash.notice = nil
  end


  # Index request for JSON needs to pass a CSRF token in order to prevent JSON Hijacking
  def check_json_authenticity
    return unless request.format.js? or request.format.json?
    auth_token = params[request_forgery_protection_token]
    unless (auth_token and form_authenticity_token == auth_token.gsub(' ', '+'))
      raise(ActionController::InvalidAuthenticityToken)
    end
  end

  private


  def load_retailer
    @retailer = Retailer.find(current_user)
    @stores = @retailer.stores
  end


end

app/controllers/retailer/images_controller.rb
class Retailer::ImagesController < Retailer::BaseController
  resource_controller
  before_filter :load_data


  new_action.response do |wants|
    wants.html { render :action => :new, :layout => false }
  end

  create.response do |wants|
    wants.html { redirect_to retailer_product_images_url(@product) }
  end

  update.response do |wants|
    wants.html { redirect_to retailer_product_images_url(@product) }
  end

  create.before :set_viewable
  update.before :set_viewable
  destroy.before :destroy_before

  destroy.response do |wants|
    wants.html do
      render :text => ""
    end
  end

  def update_positions
    params[:positions].each do |id, index|
      Image.update_all(['position=?', index], ['id=?', id])
    end

    respond_to do |format|
      format.js { render :text => 'Ok' }
    end
  end

  private

  def load_data
    @product = Product.find_by_permalink(params[:product_id])
    @variants = @product.variants.collect do |variant|
      [variant.options_text, variant.id]
    end
    @variants.insert(0, [I18n.t("all"), "All"])
  end

  def set_viewable
    if params[:image].has_key? :viewable_id
      if params[:image][:viewable_id] == "All"
        object.viewable = @product
      else
        object.viewable_type = 'Variant'
        object.viewable_id = params[:image][:viewable_id]
      end
    else
      object.viewable = @product
    end
  end

  def destroy_before
    @viewable = object.viewable
  end


end

app/controllers/retailer/option_types_controller.rb
class Retailer::OptionTypesController < Retailer::BaseController
  resource_controller

  before_filter :load_object, :only => [:selected, :available, :remove]
  belongs_to :product

  def available
    set_available_option_types
    render :layout => false
  end

  def selected
    @option_types = @product.option_types
  end

  def remove
    @product.option_types.delete(@option_type)
    @product.save
    flash.notice = I18n.t("notice_messages.option_type_removed")
    redirect_to selected_admin_product_option_types_url(@product)
  end

  new_action.response do |wants|
    wants.html {render :action => :new, :layout => !request.xhr?}
  end

  # redirect to index (instead of r_c default of show view)
  create.response do |wants|
    wants.html {redirect_to edit_object_url}
  end

  # redirect to index (instead of r_c default of show view)
  update.response do |wants|
    wants.html {redirect_to collection_url}
  end

  destroy.success.wants.js { render_js_for_destroy }

  # AJAX method for selecting an existing option type and associating with the current product
  def select
    @product = Product.find_by_param!(params[:product_id])
    product_option_type = ProductOptionType.new(:product => @product, :option_type => OptionType.find(params[:id]))
    product_option_type.save
    @product.reload
    @option_types = @product.option_types
    set_available_option_types
  end

  private
    def set_available_option_types
      @available_option_types = OptionType.all
      selected_option_types = []
      @product.options.each do |option|
        selected_option_types << option.option_type
      end
      @available_option_types.delete_if {|ot| selected_option_types.include? ot}
    end
end

app/controllers/retailer/orders_controller.rb
class Retailer::OrdersController < Retailer::BaseController
  require 'spree/gateway_error'
  resource_controller
  before_filter :initialize_txn_partials
  before_filter :initialize_order_events
  before_filter :load_object, :only => [:fire, :resend, :history, :user]
  before_filter :ensure_line_items, :only => [:update]

  update do
    flash nil
    wants.html do
      if !@order.line_items.empty?
        unless @order.complete?

          if params[:order].key?(:email)
            @order.shipping_method = @order.available_shipping_methods(:front_end).first
            @order.create_shipment!
            redirect_to edit_retailer_order_shipment_path(@order, @order.shipment)
          else
            redirect_to user_retailer_order_path(@order)
          end

        else
          redirect_to retailer_order_path(@order)
        end
      else
        render :action => :new
      end
    end
  end

  index.before do

    @orders = @search.where(:retailer_id => current_user.id)

    @orders = @orders.paginate(:page => params[:page])

  end

  show do
    @product = Product.first
  end



  def new
    @order = @object = Order.create
  end

  def fire
    # TODO - possible security check here but right now any admin can before any transition (and the state machine
    # itself will make sure transitions are not applied in the wrong state)
    event = params[:e]
    if @order.send("#{event}")
      flash.notice = t('order_updated')
    else
      flash[:error] = t('cannot_perform_operation')
    end
  rescue Spree::GatewayError => ge
    flash[:error] = "#{ge.message}"
  ensure
    redirect_to :back
  end

  def resend
    OrderMailer.confirm_email(@order, true).deliver
    flash.notice = t('order_email_resent')
    redirect_to :back
  end

  def user
    @order.build_bill_address(:country_id => Spree::Config[:default_country_id]) if @order.bill_address.nil?
    @order.build_ship_address(:country_id => Spree::Config[:default_country_id]) if @order.ship_address.nil?
  end

  private

  def object
    @object ||= Order.find_by_number(params[:id], :include => :adjustments) if params[:id]
    return @object || current_order
  end

  def collection
    params[:search] ||= {}
    @show_only_completed = params[:search][:completed_at_is_not_null].present?
    params[:search][:meta_sort] ||= @show_only_completed ? 'completed_at.desc' : 'created_at.desc'


    if !params[:search][:created_at_greater_than].blank?
      params[:search][:created_at_greater_than] = Time.zone.parse(params[:search][:created_at_greater_than]).beginning_of_day rescue ""
    end

    if !params[:search][:created_at_less_than].blank?
      params[:search][:created_at_less_than] = Time.zone.parse(params[:search][:created_at_less_than]).end_of_day #rescue ""
    end

    if @show_only_completed
      params[:search][:completed_at_greater_than] = params[:search].delete(:created_at_greater_than)
      params[:search][:completed_at_less_than] = params[:search].delete(:created_at_less_than)
    end

    @search = Order.metasearch(params[:search])


    @collection = Order.metasearch(params[:search]).paginate(
                                   :include  => [:user, :shipments, :payments],
                                   :per_page => Spree::Config[:orders_per_page],
                                   :page     => params[:page])
  end

  # Allows extensions to add new forms of payment to provide their own display of transactions
  def initialize_txn_partials
    @txn_partials = []
  end

  # Used for extensions which need to provide their own custom event links on the order details view.
  def initialize_order_events
    @order_events = %w{cancel resume}
  end

  def ensure_line_items
    load_object
    if @order.line_items.empty?
      @order.errors.add(:line_items, t('errors.messages.blank'))
      render :edit
    end
  end

end

app/controllers/retailer/payments_controller.rb
class Retailer::PaymentsController < Retailer::BaseController
  before_filter :load_data
  before_filter :load_amount, :except => :country_changed
  resource_controller
  belongs_to :order

  def create
    build_object
    load_object

    begin
      unless @payment.save
        response_for :create_fails
        return
      end

      if @order.completed?
        @payment.process!
        set_flash :create
        redirect_to collection_path
      else
        #This is the first payment (admin created order)
        until @order.completed?
          @order.next!
        end
        flash.notice = t('new_order_completed')
        redirect_to admin_order_url(@order)
      end

    rescue Spree::GatewayError => e
      flash[:error] = "#{e.message}"
      redirect_to new_object_path
    end
  end

  def fire
    # TODO: consider finer-grained control for this type of action (right now anyone in admin role can perform)
    load_object
    return unless event = params[:e] and @payment.payment_source
    if @payment.payment_source.send("#{event}", @payment)
      flash.notice = t('payment_updated')
    else
      flash[:error] = t('cannot_perform_operation')
    end
  rescue Spree::GatewayError => ge
    flash[:error] = "#{ge.message}"
  ensure
    redirect_to collection_path
  end

  private

  def object
    @object ||= Payment.find(param) unless param.nil?
    @object
  end

  def object_params
    if params[:payment] and params[:payment_source] and source_params = params.delete(:payment_source)[params[:payment][:payment_method_id]]
      params[:payment][:source_attributes] = source_params
    end
    params[:payment]
  end

  def load_data
    load_object
    @payment_methods = PaymentMethod.available(:back_end)
    if object and object.payment_method
      @payment_method = object.payment_method
    else
      @payment_method = @payment_methods.first
    end
    @previous_cards = @order.creditcards.with_payment_profile
  end

  def load_amount
    @amount = params[:amount] || @order.total
  end

  def build_object
    @object = model.new(object_params)
    @object.order = parent_object
    if @object.payment_method.is_a?(Gateway) and @object.payment_method.payment_profiles_supported? and params[:card].present? and params[:card] != 'new'
      @object.source = Creditcard.find_by_id(params[:card])
    end
    @object
  end

end

app/controllers/retailer/product_properties_controller.rb
class Retailer::ProductPropertiesController < Retailer::BaseController
  resource_controller
  before_filter :find_properties
  
  # note: we're using attribute_fu to manage the product_properties so the products controller will be 
  # doing most of the work  
  belongs_to :product
  
  private
  
  def find_properties
    @properties = Property.all.map(&:name).join(" ")
  end
end

app/controllers/retailer/settings_controller.rb
class Retailer::SettingsController < Retailer::BaseController

  skip_authorize_resource

  def show
    authorize! :show, :settings
  end


end

app/controllers/retailer/shipping_categories_controller.rb
class Retailer::ShippingCategoriesController < Retailer::BaseController
  resource_controller

  layout 'admin'

  update.response do |wants|
    wants.html { redirect_to collection_url }
  end

  create.response do |wants|
    wants.html { redirect_to collection_url }
  end

  destroy.success.wants.js { render_js_for_destroy }

end

app/views/retailer/shared/_additional_field.html.erb
<p>
  <%= label controller.controller_name.singularize, field[:name], t("activerecord.attributes.variant." + field[:name].downcase, :default => field[:name].titleize)%><br />
  <%= additional_field_for(controller, field) %>
  <%= error_message_on controller.controller_name.singularize, attribute_name_for(field[:name]) %>
</p>

app/views/retailer/shared/_address.html.erb
<p>
  <%="#{address.firstname} #{address.lastname} (#{address.phone}" %><%= address.alternative_phone unless address.alternative_phone.blank? %>)<br />
  <%= address.address1 %> <%= ", #{address.address2}" unless address.address2.blank? %>
  <%= ", #{address.city}, #{address.state_text}, #{address.zipcode}, #{address.country.name}" %>
</p>

app/views/retailer/shared/_adjustments_table.html.erb
<table class="index">
  <tr>
    <th><%= "#{t('spree.date')}/#{t('spree.time')}" %></th>
    <th><%= t("description") %></th>
    <th><%= t("amount") %></th>
    <th></th>
  </tr>
  <% @order.adjustments.each do |adjustment| %>
    <tr id="<%= dom_id(adjustment) %>">
      <td><%= adjustment.created_at.to_s(:date_time24) %></td>
      <td><%= adjustment.label %></td>
      <td><%= number_to_currency(adjustment.amount) %></td>
      <td>
        <%= link_to_edit adjustment %>
        &nbsp;
        <%= link_to_delete adjustment %>
      </td>

    </tr>
  <% end %>
</table>

app/views/retailer/shared/_calculator_fields.html.erb
<fieldset id="calculator_fields">
  <legend><%= t('calculator') %></legend>
  <div id="preference-settings">
    <p>
      <%= f.label(:calc_type, t("calculator")) %>
      <%= f.collection_select(:calculator_type, @calculators, :to_s, :description, {}, {:id => "calc-type"}) %>
    </p>
    <% if !@object.new_record? %>
      <div class="calculator-settings">
        <%= f.fields_for :calculator do |calculator_form| %>
          <%= preference_fields(@object.calculator, calculator_form) %>
        <% end %>
      </div>
      <% if @object.calculator.respond_to?(:preferences) %>
        <div id="calculator-settings-warning"><%= t('calculator_settings_warning')%></div>
      <% end %>
    <% end %>
  </div>
</fieldset>

app/views/retailer/shared/_configuration_menu.html.erb
<% content_for :sidebar do %>

  <h3><%= t("configurations") %></h3>
  <br class="clear" />

  <ul class="sidebar">
    <%= hook :admin_configurations_sidebar_menu do %>
    <li<%== ' class="active"' if controller.controller_name == 'general_settings' %>><%= link_to t("general_settings"), admin_general_settings_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'mail_methods' %>><%= link_to t("mail_methods"), admin_mail_methods_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'tax_categories' %>><%= link_to t("tax_categories"), admin_tax_categories_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'zones' %>><%= link_to t("zones"), admin_zones_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'states' %>><%= link_to t("states"), admin_country_states_path(Spree::Config[:default_country_id]) %></li>
    <li<%== ' class="active"' if controller.controller_name == 'payment_methods' %>><%= link_to t("payment_methods"), admin_payment_methods_path %></li>
    <li<%== ' class="active"' if ['taxonomies', 'taxons'].include? controller.controller_name %>><%= link_to t("taxonomies"), admin_taxonomies_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'shipping_methods' %>><%= link_to t("shipping_methods"), admin_shipping_methods_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'inventory_settings' %>><%= link_to t("inventory_settings"), admin_inventory_settings_path %></li>
    <li<%== ' class="active"' if controller.controller_name == 'trackers' %>><%= link_to t("analytics_trackers"), admin_trackers_path %></li>
    <% end %>
    <li<%== ' class="active"' if controller.controller_name == 'configurations' %>><%= link_to t("complete_list"), admin_configurations_path %></li>
  </ul>

<% end %>

app/views/retailer/shared/_edit_resource_links.html.erb
<p class="form-buttons">
  <%= f.submit :value => "Finish", :class => "button finish" if @current_action == "edit" %>
  <%= f.submit :value => "Next", :class => "button next" %>
  <%= link_to 'Cancel', retailer_products_url, :class => "button cancel" %>
</p>

app/views/retailer/shared/_group_from_products_form.html.erb
<% if products.any? %>
  <% form_tag retailer_product_groups_path do %>
    <%= hidden_field_tag "product_group[product_scopes_attributes][][name]", 'with_ids' %>
    <%= hidden_field_tag "product_group[product_scopes_attributes][][arguments][]", products.map(&:id).join(',') %>
    <fieldset>
      <legend><%= t('create_product_group_from_products') %></legend>
      <label><%= t('name') %></label>
      <%= text_field_tag "product_group[name]",  'New group' %>
      <input type="submit" value="<%= t('create') %>">
    </fieldset>
  <% end %>
<% end %>

app/views/retailer/shared/_jms.html.erb
<div class="sidebar_ad" id="retailer_jms_ad">
  <h3>Discover the <span>6 Secrets to Making More Profit</span> from your Jewellery Store Marketing</h3>
  <br/>
  <%= image_tag 'themargyles.jpg' %>
  <h4>Plus receive a free copy of our ebook <br/><span>"How to Effectively Market your Jewellery Store"</span></h4><br/>
  <%= link_to "Click here for Your Free E-Book", "http://www.jewellerymarketingsolutions.com", :class => "ebook_link" %>
  <hr/>
  <%= image_tag 'jms.jpg' %>
  <br/>

  <p><strong>e:</strong> admin@jewellerymarketingsolutions.com<br/>
    <strong>w:</strong> www.jewellerymarketingsolutions.com</p>
</div>

app/views/retailer/shared/_new_adjustment_button.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to t("new_adjustment"), new_retailer_order_adjustment_url(@order), :icon => 'add' %>
    </li>
  </ul>
  <br class='clear' />
</div>

app/views/retailer/shared/_order_tabs.html.erb
<h1><%= t(:order) + " #{@order.number}" %></h1>

<% content_for :sidebar do %>
  <div id="order_tab_summary">
    <h3 id="order_number"><%= "#{t(:order)} ##{@order.number} " %></h3>
    <h5 id="order_status"><%= "#{t(:status)}: #{t("order_state.#{@order.state}")}" %></h5>
    <h5 id="order_total"><%= "#{t(:total)}: #{number_to_currency(@order.total)}" %></h5>
    <% if @order.completed? %>
      <h5 id="shipment_status"><%= "#{t(:shipment)}: #{t("shipment_states.#{@order.shipment_state}")}"  %></h5>
      <h5 id="payment_status"><%= "#{t(:payment)}: #{t("payment_states.#{@order.payment_state}")}" %></h5>
    <% end %>
    <br class="clear" />
  </div>
  <br class="clear" />

  <ul class="sidebar">
    <%= hook :admin_order_tabs do %>
      <% unless @order.completed? %>
        <li<%== ' class="active"' if current == "Order Details" %>>
          <%= link_to t("order_details"), edit_retailer_order_url(@order) %>
        </li>
        <li<%== ' class="active"' if current == "Customer Details" %>>
            <%= link_to t("customer_details"), user_retailer_order_url(@order) %>
        </li>
        <!--<li<%== ' class="active"' if current == "Shipments" %>>-->
           <!--<%= link_to t("shipment"), @order.line_items.empty? || !@order.completed? ? "javascript:$('form').submit();" : edit_retailer_order_shipment_url(@order, @order.shipment) %>-->
        <!--</li>-->
        <!--<li<%== ' class="active"' if current == "Adjustments" %>>-->
           <!--<%= link_to t("adjustments"), @order.line_items.empty? || !@order.completed? ? "javascript:$('form').submit();" : retailer_order_adjustments_url(@order) %>-->
        <!--</li>-->
        <!--<li<%== ' class="active"' if current == "Payments" %>>-->
           <!--<%= link_to t("payment"), @order.line_items.empty? || !@order.completed? ? "javascript:$('form').submit();" : new_retailer_order_payment_url(@order) %>-->
        <!--</li>-->

      <% else %>
        <!--<li<%== ' class="active"' if current == "Order Details" %>>-->
          <!--<%= link_to t("order_details"), edit_retailer_order_url(@order) %>-->
        <!--</li>-->
        <!--<li<%== ' class="active"' if current == "Customer Details" %>>-->
          <!--<%= link_to t("customer_details"), user_retailer_order_url(@order) %>-->
        <!--</li>-->
        <!--<li<%== ' class="active"' if current == "Adjustments" %>>-->
           <!--<%= link_to t("adjustments"), retailer_order_adjustments_url(@order) %>-->
        <!--</li>-->
        <!--<li<%== ' class="active"' if current == "Payments" %>>-->
           <!--<%= link_to t("payments"), retailer_order_payments_url(@order) %>-->
        <!--</li>-->
        <li<%== ' class="active"' if current == "Shipments" %>>
           <%= link_to 'Sales Details', edit_retailer_order_shipment_url(@order, @order.shipment) %>
        </li>
        <!--<li<%== ' class="active"' if current == "Return Authorizations" %>>-->
           <!--<%= link_to t("return_authorizations"), retailer_order_return_authorizations_url(@order) %>-->
        <!--</li>-->
        <!--<li<%== ' class="active"' if current == "History" %>>-->
           <!--<%= link_to t("history"), history_retailer_order_url(@order) %>-->
        <!--</li>-->
      <% end %>



    <% end %>
  </ul>

<% end %>

app/views/retailer/shared/_product_tabs.html.erb
<h1><%= raw(t("editing_product") + " &ldquo;#{@product.name}&rdquo;") %></h1>

<% content_for :sidebar do %>

  <h3><%= @product.name %><span class='sku'><%= @product.sku %></span></h3>
  <br class="clear" />

  <ul class="sidebar product-menu">
    <%= hook :retailer_product_tabs, {:current => current} do %>

      <li<%== ' class="active"' if current == "Product Details" %>>
        <%= link_to t("product_details"), edit_retailer_product_url(@product) %>
      </li>
      <li<%== ' class="active"' if current == "Images" %>>
        <%= link_to t("images"), retailer_product_images_url(@product) %>
      </li>
      <!-- <li<%#== ' class="active"' if current == "Variants" %>>
        <%# link_to t("variants"),  retailer_product_variants_url(@product)  %>
      </li>
      <li<%#== ' class="active"' if current == "Option Types" %>>
        <%# link_to t("option_types"), selected_retailer_product_option_types_url(@product) %>
      </li>
      <li<%#== ' class="active"' if current == "Product Properties" %>>
        <%# link_to t("product_properties"), retailer_product_product_properties_url(@product) %>
      </li> -->
      <li<%== ' class="active"' if current == "Taxons" %>>
        <%= link_to t("taxons"), selected_retailer_product_taxons_url(@product) %>
      </li>

    <% end %>
  </ul>
  <br class="clear" />

<% end %>

app/views/retailer/shared/_report_criteria.html.erb
<%= form_for @search, :url => sales_total_retailer_reports_path do |s| %>
    <label><%= t("date_range") %></label><br />
    <div class="yui-g date-range-filter">
      <div class="yui-u sub-field first">
        <%= s.spree_date_picker :created_at_greater_than %><br />
        <label class="sub"><%= t("start") %></label>
      </div>
      <div class="yui-u sub-field">
        <%= s.spree_date_picker :created_at_less_than %><br />
        <label><%= t("stop") %></label>
      </div>
    </div>

    <p><%= button t("search") %></p>
<% end %>

app/views/retailer/shared/_show_resource_links.html.erb
<p class="actions">
<%= link_to t("edit"), edit_object_url %> |
<%= link_to t("back"), collection_url %> |
<%= link_to t("delete"), object_url, :confirm => t('are_you_sure_you_want_to_delete_this_record'), :method => :delete %>
</p>