config/routes.rb
Jewellover::Application.routes.draw do

  get "lists_controller/index"

  resources :wallets
  resources :authentications

  devise_for :retailer, :controllers => {:registrations => "retailer/registrations"}, :skip => [:sessions, :password] do
    get "retailer/signup" => "retailer/registrations#new"
  end

  match '/auth/:provider/callback', :to => 'authentications#create'
  match '/auth/failure', :to => 'authentications#failure'

  match "/notify_url" => "paypal_adaptive_payment_callbacks#notify", :as => :paypal_notify
  resources :paypal_adaptive_payment_callbacks

  resources :bids
  resource :user_preferences
  resources :stores do
    resources :products, :only => [:index, :show]
  end

  resource :contact do
    post :store
  end

  match "/" => "products#homepage"
  match "/products" => "products#index"
  match "/categories" => "products#categories"
  match "/upcoming" => "products#upcoming"
  match "/recent" => "products#latest"

  match "/testimonials" => "posts#testimonials"
  match "/whats_new" => "posts#whats_new"

  match "/my_dashboard" => "dashboard#index", :as => :my_dashboard
  match "/my_orders" => "orders#index", :as => :my_orders
  match "/my_offers" => "bids#index", :as => :my_offers
  match "/my_watchlist" => "watchlists#index", :as => :my_watchlist
  match "/my_account" => "users#edit", :as => :my_account
  match "/my_wallet" => "wallets#show", :as => :my_wallet

  match "/server_time" => "spree/base#server_time"
  match "/site_product_info" => "spree/base#site_product_info"
  match "/products/view_style" => "products#view_style"

  match "/v2" => "products#homepage"

  match '/users/add_product_to_watchlist' => 'users#add_product_to_watchlist', :via => :post
  match '/users/remove_product_from_watchlist' => 'users#remove_product_from_watchlist', :via => :post

  match '/t/*id' => 'taxons#show', :as => :nested_taxons

  namespace :api do

    match "/taxonomies" => "products#taxonomies"

    resources :retailers, :only => [:show, :index] do
      resources :products, :only => [:show, :index, :create, :update] do
        match "/images/:image_id" => "products#delete_image", :via => :delete
      end
    end
    resources :products, :only => [:index, :show]

  end

  namespace :admin do

    resources :lists do
      member do
        match "upload_csv" => "lists#upload_csv"
        get :download_csv
      end

      resources :list_recipients, :except => [:edit, :update, :show], :as => :contacts
    end
    resources :coupons
    resources :posts
    resources :users do
      post :toggle_ban, :on => :member
    end
    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        get :leveredge_total
      end
    end
    resources :stores do
      member do
        post :toggle_website
        post :toggle_facebook
      end
    end
    resources :products do
      member do
        post :product_campaign
        post :toggle_relist
        get :reset
      end
    end

  end

  namespace :retailer do

    match "/" => 'products#index'
    match "/support" => 'static#support', :as => :support

    resource :retailer_detail
    resource :settings

    resources :stores
    resources :zones
    resources :users
    resources :countries do
      resources :states
    end
    resources :states
    resources :promotions
    resources :tax_categories
    resources :configurations
    resources :products do
      member do
        get :clone
        get :finish
        get :start
        post :archive
        post :toggle_relist
        post :refund
      end
      resources :product_properties
      resources :images
      resources :variants
      resources :option_types do
        member do
          get :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
      resources :taxons do
        member do
          get :select
          delete :remove
          get :finish
        end
        collection do
          post :available
          get :selected
        end
      end
    end
    resources :option_types
    resources :properties do
      collection do
        get :filtered
      end
    end
    resources :prototypes do
      member do
        get :select
      end
      collection do
        get :available
      end
    end
    resource :inventory_settings
    resources :google_analytics
    resources :orders do
      member do
        put :fire
        get :fire
        post :resend
        get :history
        get :user
      end
      resources :adjustments
      resources :line_items
      resources :shipments do
        member do
          put :fire
        end
      end
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end
    resource :general_settings
    resources :taxonomies do
      member do
        get :get_children
      end
      resources :taxons
    end
    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
      end
    end
    resources :shipments
    resources :shipping_methods
    resources :shipping_categories
    resources :tax_rates
    resource :tax_settings
    resources :calculators
    resources :product_groups do
      resources :product_scopes
    end
  end

end

app/controllers/retailer/images_controller.rb
class Retailer::ImagesController < Retailer::BaseController
  resource_controller
  before_filter :load_data


  new_action.response do |wants|
    wants.html { render :action => :new, :layout => false }
  end

  create.response do |wants|
    wants.html { redirect_to retailer_product_images_url(@product) }
  end

  update.response do |wants|
    wants.html { redirect_to retailer_product_images_url(@product) }
  end

  create.before :set_viewable
  update.before :set_viewable
  destroy.before :destroy_before

  destroy.response do |wants|
    wants.html do
      render :text => ""
    end
  end

  def update_positions
    params[:positions].each do |id, index|
      Image.update_all(['position=?', index], ['id=?', id])
    end

    respond_to do |format|
      format.js { render :text => 'Ok' }
    end
  end

  private

  def load_data
    @product = Product.find_by_permalink(params[:product_id])
    @variants = @product.variants.collect do |variant|
      [variant.options_text, variant.id]
    end
    @variants.insert(0, [I18n.t("all"), "All"])
  end

  def set_viewable
    if params[:image].has_key? :viewable_id
      if params[:image][:viewable_id] == "All"
        object.viewable = @product
      else
        object.viewable_type = 'Variant'
        object.viewable_id = params[:image][:viewable_id]
      end
    else
      object.viewable = @product
    end
  end

  def destroy_before
    @viewable = object.viewable
  end


end

app/views/admin/images/_form.html.erb
<tr>
  <td><%= t("filename") %>:</td>
  <td><%= f.file_field :attachment %></td>
</tr>
<% if @product.has_variants? %>
  <tr>
    <td><%= Variant.model_name.human %>:</td>
    <td><%= f.select :viewable_id, @variants %></td>
  </tr>
<% else %>
  <%= hidden_field_tag :product_id, @product.id %>
<% end %>
<tr>
  <td><%= t("alt_text") %>:</td>
  <td><%= f.text_area :alt %></td>
</tr>

app/views/admin/images/edit.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<%= render :partial => 'admin/shared/product_tabs', :locals => {:current => "Images"} %>

<%= render "shared/error_messages", :target => @image %>

<%= form_for(:image, :url => admin_product_image_url(@product), :html => { :method => :put, :multipart => true }) do |f| %>
  <table class="basic-table">
    <tr>
      <td><%= t("thumbnail") %>:</td>
      <td><%= link_to(image_tag(@image.attachment.url(:mini)), @image.attachment.url(:product)) %></td>
    </tr>
    <%= render :partial => "form", :locals => { :f => f } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), admin_product_images_url(@product), :id => "cancel_link" %>
  </p>
<% end %>

app/views/admin/images/index.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<%= render :partial => 'admin/shared/product_tabs', :locals => {:current => "Images"} %>

<table class="index sortable">
  <tr>
    <th><%= t("thumbnail") %></th>
    <% if @product.has_variants? %>
      <th><%= Variant.model_name.human %></th>
    <% end %>
    <th><%= t("alt_text") %></th>
    <th><%= t("action") %></th>
  </tr>

  <% @product.images.each do |image| %>
    <tr id="<%= dom_id(image) %>">
      <td>
        <span class="handle"></span>
        <%= link_to(image_tag(image.attachment.url(:mini)), image.attachment.url(:product)) %>
      </td>
      <% if @product.has_variants? %>
        <td><%= t('all') %></td>
      <% end %>
      <td><%= image.alt %></td>
      <td class="actions">
        <%= link_to_with_icon('edit', t("edit"), edit_admin_product_image_url(@product, image), :class => 'edit') %>
        &nbsp;
        <%= link_to_delete image, {:url => admin_product_image_url(@product, image) }%>
      </td>
    </tr>
  <% end %>

  <% @product.variants.each do |variant| %>
    <% variant.images.each do |image| %>
      <tr id="<%= dom_id(image) %>">
        <td><span class="handle"></span><%= link_to(image_tag(image.attachment.url(:mini)), image.attachment.url(:product)) %></td>
        <% if @product.has_variants? %>
          <td><%= variant.options_text %></td>
        <% end %>
        <td><%= image.alt %></td>
        <td class="actions">
          <%= link_to_with_icon('edit', t("edit"), edit_admin_product_image_url(@product, image)) %>
          &nbsp;
          <%= link_to_delete image, {:url => admin_product_image_url(@product, image) }%>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

<div id="images"></div>
<br/>
<p>
    <%= link_to icon('add') + ' ' + t("new_image"), new_admin_product_image_url(@product), :id => "new_image_link" %>
</p>

<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){

      jQuery('#new_image_link').click(function (event) {
        event.preventDefault();
        jQuery(this).hide();
        jQuery.ajax({type: 'GET', url: this.href, data: ({authenticity_token: AUTH_TOKEN}), success: function(r){ jQuery('#images').html(r);} });
      });

    });
  </script>
<% end %>

app/views/admin/images/new.html.erb
<h4><%= t("new_image") %></h4>
<%= form_for(:image, :url => { :controller => 'images', :action => 'create' }, :html => { :multipart => true }) do |form| %>
  <table class="basic-table">
    <%= render :partial => "form", :locals => { :f => form } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), "#", :id => "cancel_link" %>
  </p>
<% end %>


<script type="text/javascript">    
  jQuery('#cancel_link').click(function (event) { 
    jQuery('#new_image_link').show();
    jQuery('#images').html('');
  });  
 
</script>

 
 